config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get 'coming_events' => 'pages#events'
  get 'blog' => 'pages#blog'
  get 'contact' => 'pages#contact_us'
  get 'pictures' => 'pages#gallery'
  get 'show_gallery' => 'pages#show_gallery'
  get 'about_me' => 'pages#about_me'
  resources :events
  resources :galleries
  resources :blog_entries
  resources :music_tracks
  resources :images
  resources :copies
  resources :slides
  devise_scope :user do
    get "/admin" => "devise/sessions#new"
  end
end

app/models/blog_entry.rb
# == Schema Information
#
# Table name: blog_entries
#
#  id                 :integer          not null, primary key
#  title              :string
#  author             :string
#  content            :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class BlogEntry < ActiveRecord::Base
  has_attached_file :image, styles: { index_size: "990x500#", show_size: "1170x500#", thumb: "100x100#" }, default_url: "http://i592.photobucket.com/albums/tt5/Mardini03/imagen-no-disponible.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :title, :author, :content, :image, presence: { message: "Todos los campos son obligatorios"}
end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  before_action :authenticate_user!, :except => [:show]

  def new
    @blog_entry = BlogEntry.new
  end

  def create
    @blog_entry = BlogEntry.new(blog_entry_params)
    if @blog_entry.save
      flash[:notice] = "La entrada de blog ha sido guardada con éxito"
      redirect_to blog_entries_path
    else
      flash[:alert] = "Ha ocurrido un problema y la entrada de blog no ha sido almacenada"
      render :action => 'new'
    end
  end

  def edit
    @blog_entry = BlogEntry.find(params[:id])
  end

  def update
    @blog_entry = BlogEntry.find(params[:id])
    if @blog_entry.update(blog_entry_params)
      flash[:notice] = "La entrada de blog ha sido editada con éxito"
      redirect_to blog_entries_path
    else
      flash[:alert] = 'Ha ocurrido un problema y la entrada de blog no ha sido editada'
      render 'edit'
    end
  end

  def show
    @blog_entry = BlogEntry.find(params[:id])
  end

  def index
    @blog_entries = BlogEntry.all.order(created_at: :desc)
  end

  def destroy
    @blog_entry = BlogEntry.find(params[:id])
    @blog_entry.destroy
    redirect_to blog_entries_path
  end

  private
    def blog_entry_params
      params.require(:blog_entry).permit(:title, :author, :image, :content)
    end
end

app/helpers/blog_entries_helper.rb
module BlogEntriesHelper
end

app/views/blog_entries/_blog_entry_fields.html.erb
<div class="field form-group">
  <%= blog_entry.label :title, "Título:", class: "lead lead-lg" %>
  <%= blog_entry.text_field :title, required: true, class: "form-control", id: "new_user_email" %>
</div>

<div class="field form-group">
  <%= blog_entry.label :author, "Autor:", class: "lead lead-lg" %>
  <%= blog_entry.text_field :author, required: true, class: "form-control", id: "new_user_email" %>
</div>

<div class="field form-group">
  <%= blog_entry.label :content, "Contenido:", class: "lead lead-lg" %>
  <%= blog_entry.text_area :content, required: true, :rows => 15, class: "form-control wysihtml5", id: "new_user_email" %>
</div>

<div class="field form-group">
  <%= blog_entry.label :image, "Imagen:", class: "lead lead-lg block-label" %>
  <% if @blog_entry.image.url != "http://i592.photobucket.com/albums/tt5/Mardini03/imagen-no-disponible.png" %>
    <div class="col-md-12">
      <div class="col-md-3">
        <%= image_tag blog_entry.object.image.url(:thumb) %>
      </div>
      <div class="col-md-9">
        <div class="form-group reg-email">
          <div>
            <%= blog_entry.file_field :image, class: "input-file" %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <%= blog_entry.file_field :image, required: true, class: "input-file" %>
  <% end %>
</div>

<div class="actions form-group text-center">
  <%= link_to "Cancelar", blog_entries_path, :class => 'btn btn-lg btn-danger' %>
  <%= blog_entry.submit "Guardar Información", :class => 'btn btn-lg btn-success' %>
</div>

app/views/blog_entries/edit.html.erb
<div class="container new_register">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Editar entrada de blog:</h1>
      <%= form_for(@blog_entry) do |blog_entry| %>
        <% if @blog_entry.errors.any? %>
          <% @blog_entry.errors.each do |attribute, message| %>
            <h3 class="validation-error"><%= message %></h3>
          <% end %>
        <% end %>
        <%= render 'blog_entry_fields', blog_entry: blog_entry %>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){

    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })
</script>

app/views/blog_entries/index.html.erb
<div class="container new_register">
  <div class="row">
    <h1 class="text-center">Entradas de Blog</h1>
    <div class="col-md-12">
      <table class="table">
        <thead>
          <th>Número</th>
          <th>Imagen</th>
          <th>Título</th>
          <th>Fecha</th>
          <th>Opciones</th>
        </thead>
        <% @blog_entries.each_with_index do |blog_entry,index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= image_tag blog_entry.image.url(:thumb) %></td>
            <td><%= blog_entry.title %></td>
            <td><%= blog_entry.created_at.strftime("%B %d, %Y") %></td>
            <td><%= link_to "Ver", blog_entry_path(blog_entry) %> - <%= link_to "Editar", edit_blog_entry_path(blog_entry) %> - <%= link_to blog_entry_path(blog_entry.id), method: :delete, data: { confirm: '¿Are you sure?' } do %>Eliminar<% end %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 text-center col-md-offset-3" id="btn-new-user">
      <%= link_to "Regresar al Home", root_path, :class => 'btn btn-lg btn-danger' %>
      <%= link_to "Crear nueva entrada", new_blog_entry_path, class: "btn btn-lg btn-ar btn-success" %>
    </div>
</div>

app/views/blog_entries/new.html.erb
<div class="container new_register">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Crear nueva entrada de blog:</h1>
      <%= form_for(@blog_entry) do |blog_entry| %>
        <% if @blog_entry.errors.any? %>
          <% @blog_entry.errors.each do |attribute, message| %>
            <h3 class="validation-error"><%= message %></h3>
          <% end %>
        <% end %>
        <%= render 'blog_entry_fields', blog_entry: blog_entry %>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){

    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })
</script>

app/views/blog_entries/show.html.erb
<%= render 'layouts/navbar', other_page: true %>
<!--page title start-->
<div class="rock_page_title_main">
  <%= render 'pages/rock_page_title_bg' %>
  <div class="rock_page_title">
    <div class="container">
      <div class="rock_heading_div">
        <div class="rock_heading">
          <h1>Leer Entrada</h1>
          <p>X</p>
        </div>
      </div>
      <div class="rock_pager">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Leer entrada", blog_entry_path(@blog_entry) %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--page title end-->
<div class="clearfix"></div>
<div class="rock_margin_30"></div>

<!--main content start-->
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="rock_blog_single"> <img src="<%= @blog_entry.image.url(:show_size) %>" alt="blog single" />
        <h2><%= @blog_entry.title %></h2>
        <div class="blog_entry_meta">
          <ul>
            <li><%= link_to "<i class='fa fa-user'></i>#{@blog_entry.author}".html_safe, blog_entry_path(@blog_entry) %></li>
            <li><%= link_to "<i class='fa fa-calendar'></i>#{@blog_entry.created_at.strftime("%B %d, %Y")}".html_safe, blog_entry_path(@blog_entry) %></li>
          </ul>
        </div>
        <hr>
        <p><%= @blog_entry.content.html_safe %></p>
      </div>
    </div>
  </div>
</div>

<div class="clearfix" style="margin-top: 60px;"></div>
<%= render 'layouts/footer' %>