config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get 'coming_events' => 'pages#events'
  get 'blog' => 'pages#blog'
  get 'contact' => 'pages#contact_us'
  get 'pictures' => 'pages#gallery'
  get 'show_gallery' => 'pages#show_gallery'
  get 'about_me' => 'pages#about_me'
  resources :events
  resources :galleries
  resources :blog_entries
  resources :music_tracks
  resources :images
  resources :copies
  resources :slides
  devise_scope :user do
    get "/admin" => "devise/sessions#new"
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                 :integer          not null, primary key
#  event_date         :datetime
#  title              :string
#  start_hour         :time
#  end_hour           :time
#  location           :string
#  description        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Event < ActiveRecord::Base
  scope :reversed, -> { order 'created_at DESC' }

  has_attached_file :image, styles: { medium: "570x330#", thumb: "100x100#", home_size: "495x330#" }, default_url: "http://i592.photobucket.com/albums/tt5/Mardini03/imagen-no-disponible.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :title, :event_date, :start_hour, :end_hour, :location, :description, :image, presence: { message: "Todos los campos son obligatorios"}
  validates :description, length: { maximum: 145,
    too_long: "%{count} caracteres es el máximo permitido" }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "El evento ha sido guardado con éxito"
      redirect_to events_path
    else
      flash[:alert] = "Ha ocurrido un problema y el evento no ha sido almacenado"
      render :action => 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:notice] = "El evento ha sido editado con éxito"
      redirect_to events_path
    else
      flash[:alert] = 'Ha ocurrido un problema y el evento no ha sido almacenado'
      render 'edit'
    end
  end

  def index
    @events = Event.all.order(created_at: :desc)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(:title, :event_date, :start_hour, :end_hour, :location, :description, :image)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_fields.html.erb
<div class="field form-group">
  <%= event.label :title, "Nombre:", class: "lead lead-lg" %>
  <%= event.text_field :title, required: true, class: "form-control", id: "new_user_email" %>
</div>

<div class="field form-group">
  <%= event.label :event_date, "Fecha:", class: "lead lead-lg block-label" %>
  <%= event.date_select :event_date, {ampm: true, minute_step: 15, :default => {:hour => '06', :minute => '00'} }, required: true, class: "form-control half-width" %>
</div>

<div class="field form-group">
  <%= event.label :location, "Locación:", class: "lead lead-lg" %>
  <%= event.text_field :location, required: true, class: "form-control", id: "new_user_email" %>
</div>

<div class="field form-group">
  <%= event.label :description, "Descripción:", class: "lead lead-lg" %>
  <%= event.text_area :description, required: true, :rows => 5, class: "form-control", id: "new_user_email" %>
</div>

<div class="field form-group">
  <%= event.label :image, "Imagen:", class: "lead lead-lg block-label" %>
  <% if @event.image.url != "http://i592.photobucket.com/albums/tt5/Mardini03/imagen-no-disponible.png" %>
    <div class="col-md-12">
      <div class="col-md-3">
        <%= image_tag event.object.image.url(:thumb) %>
      </div>
      <div class="col-md-9">
        <div class="form-group reg-email">
          <div>
            <%= event.file_field :image, class: "input-file" %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <%= event.file_field :image, required: true, class: "input-file" %>
  <% end %>
</div>

<div class="field form-group">
  <%= event.label :start_hour, "Hora de Inicio:", class: "lead lead-lg block-label" %>
  <%= event.time_select :start_hour, {ampm: true, minute_step: 15, :default => {:hour => '06', :minute => '00'} }, required: true, class: "form-control half-width" %>
</div>

<div class="field form-group">
  <%= event.label :end_hour, "Hora de Cierre:", class: "lead lead-lg block-label" %>
  <%= event.time_select :end_hour, {ampm: true, minute_step: 15, :default => {:hour => '06', :minute => '00'} }, required: true, class: "form-control half-width" %>
</div>

<div class="actions form-group text-center">
  <%= link_to "Cancelar", events_path, :class => 'btn btn-lg btn-danger' %>
  <%= event.submit "Guardar Información", :class => 'btn btn-lg btn-success' %>
</div>

app/views/events/edit.html.erb
<div class="container new_register">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Editar evento:</h1>
      <%= form_for(@event) do |event| %>
        <% if @event.errors.any? %>
          <% @event.errors.each do |attribute, message| %>
            <h3 class="validation-error"><%= message %></h3>
          <% end %>
        <% end %>
        <%= render 'event_fields', event: event %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container new_register">
  <div class="row">
    <h1 class="text-center">Eventos</h1>
    <div class="col-md-12">
      <table class="table">
        <thead>
          <th>Número</th>
          <th>Imagen</th>
          <th>Título</th>
          <th>Fecha</th>
          <th>Horario</th>
          <th>Opciones</th>
        </thead>
        <% @events.each_with_index do |event,index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= image_tag event.image.url(:thumb) %></td>
            <td><%= event.title %></td>
            <td><%= event.event_date.strftime("%B %d, %Y") %></td>
            <td><%= event.start_hour.strftime("%l %p") %> a <%= event.end_hour.strftime("%l %p") %></td>
            <td><%= link_to "Editar", edit_event_path(event) %> - <%= link_to event_path(event.id), method: :delete, data: { confirm: '¿Are you sure?' } do %>Eliminar<% end %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 text-center col-md-offset-3" id="btn-new-user">
      <%= link_to "Regresar al Home", root_path, :class => 'btn btn-lg btn-danger' %>
      <%= link_to "Crear evento", new_event_path, class: "btn btn-lg btn-ar btn-success" %>
    </div>
</div>

app/views/events/new.html.erb
<div class="container new_register">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Crear nuevo evento:</h1>
      <%= form_for(@event) do |event| %>
        <% if @event.errors.any? %>
          <% @event.errors.each do |attribute, message| %>
            <h3 class="validation-error"><%= message %></h3>
          <% end %>
        <% end %>
        <%= render 'event_fields', event: event %>
      <% end %>
    </div>
  </div>
</div>