config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get 'coming_events' => 'pages#events'
  get 'blog' => 'pages#blog'
  get 'contact' => 'pages#contact_us'
  get 'pictures' => 'pages#gallery'
  get 'show_gallery' => 'pages#show_gallery'
  get 'about_me' => 'pages#about_me'
  resources :events
  resources :galleries
  resources :blog_entries
  resources :music_tracks
  resources :images
  resources :copies
  resources :slides
  devise_scope :user do
    get "/admin" => "devise/sessions#new"
  end
end

app/views/pages/_rock_page_title_bg.html.erb
<div class="rock_page_title_bg">
  <section class="main">
    <div id="rock_page_title_bg" class="ri-grid ri-grid-size-3">
      <ul>
        <% @header_images.each do |background_image| %>
          <li><a href="#"><img src="<%= background_image.image.url(:medium) %>" alt="" /></a></li>
        <% end %>
      </ul>
    </div>
  </section>
</div>

app/views/pages/about_me.html.erb
<%= render 'layouts/navbar', other_page: true %>
<!--page title start-->
<div class="rock_page_title_main">
  <%= render 'rock_page_title_bg' %>
  <div class="rock_page_title">
    <div class="container">
      <div class="rock_heading_div">
        <div class="rock_heading">
          <h1>Quién Soy?</h1>
          <p>X</p>
        </div>
      </div>
      <div class="rock_pager">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Quién Soy?", about_me_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--page title end-->
<div class="clearfix"></div>
<div class="rock_margin_30"></div>
<div class="container">
  <div class="row">

    <div class="col-lg-12 col-md-12 col-sm-12 rock_about" style="margin-bottom: 70px;">
      <div class="rock_about_welcome">
        <h1 class="rock_welcome"><strong><%= @copies.home_title_1 %></strong></h1>
      </div>
      <img src="<%= Slide.find(4).image.url(:extra_large) %>" alt="" />
      <%= @copies.who_i_am.html_safe %>
    </div>

  </div>
</div>
<div class="clearfix"></div>
<%= render 'layouts/footer' %>

app/views/pages/blog.html.erb
<%= render 'layouts/navbar', other_page: true %>
<!--page title start-->
<div class="rock_page_title_main">
  <%= render 'rock_page_title_bg' %>
  <div class="rock_page_title">
    <div class="container">
      <div class="rock_heading_div">
        <div class="rock_heading">
          <h1>Entradas de Blog</h1>
          <p>X</p>
        </div>
      </div>
      <div class="rock_pager">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Entradas de Blog", blog_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--page title end-->
<div class="blogcategory_container">
  <div class="col-lg-8 col-md-7 col-sm-8 blogcategory_big_part">
    <% @blog_entries.each do |blog_entry| %>
      <div class="rock_blog">
        <div class="blogcategory_image"> <img src="<%= blog_entry.image.url(:index_size) %>" alt="" />
          <div class="blogcategory_image_overlay">
            <div class="photo_link"> <%= link_to "<i class='fa fa-link'></i>".html_safe, blog_entry_path(blog_entry) %> </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-10 col-md-10 col-sm-10 col-lg-offset-2 col-md-offset-2 col-sm-offset-2">
            <div class="rock_blog_detail">
              <h3><%= blog_entry.title %></h3>
              <div class="blog_entry_meta">
                <ul>
                  <li><%= link_to "<i class='fa fa-user'></i>#{blog_entry.author}".html_safe, blog_entry_path(blog_entry) %></li>
                  <li><%= link_to "<i class='fa fa-calendar'></i>#{blog_entry.created_at.strftime("%B %d, %Y")}".html_safe, blog_entry_path(blog_entry) %></li>
                </ul>
              </div>
              <!-- <p>Vivamus scelerisque mauris sit amet lacus apit. Curabitur bibendum, odio sed tempus egestas, risus lacus loere velit leo a quam. Vivamus bibendum felis ac urna pellentesque, id porttitollamcorper. Vivamus vitae vulputate massa. Suspendisse scelerisques imperdiet convallis, nisi urna dapibus odio, </p> -->
              <%= link_to "Leer más", blog_entry_path(blog_entry), class: "btn btn-arrow btn-4a icon-arrow-right" %>
            <!--   <a href="" class="">Read More</a>  -->
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <!--sidebar start-->
  <div class="col-lg-4 col-md-5 col-sm-4 blogcategory_small_part">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-12">
        <div class="rock_sidebar">
          <h2>Ultima Canción</h2>
          <div class="rock_audio_player">
            <div class="rock_audio_player_title"><span class="track_artist"><%= @last_track.author %></span> <%= @last_track.name %></div>
            <div class="rock_audio_player_track_image"> <img src="<%= @last_track.image.url(:medium) %>" alt="track 1" />
              <div class="rock_audio_player_track_image_overlay"><%= @last_track.name %></div>
            </div>
            <div class="audio-player">
              <audio class="rock_player" src="<%= @last_track_audio.audio.url %>" type="audio/mp3" controls></audio>
            </div>
          </div>
        </div>
        <div class="rock_sidebar">
          <h2>Últimas Entradas</h2>
          <div class="rock_recent_post">
            <ul class="bxslider">
              <% @footer_blog_entries.each do |blog_entry| %>
                <li> <img src="<%= blog_entry.image.url(:thumb) %>" alt="post" />
                  <div class="rock_post_detail"> <%= link_to blog_entry.title, blog_entry_path(blog_entry) %>
                    <p><span class="label label-default"><%= blog_entry.created_at.strftime("%B %d, %Y") %></span></p>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="rock_sidebar">
          <h2>Galería</h2>
          <div class="rock_gallery">
            <ul>
              <% @blog_pics.each do |image| %>
                <li><a href=""><img src="<%= image.photo.url(:medium_thumb) %>" alt=""/></a></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--sidebar end-->
</div>
<div class="clearfix"></div>
<%= render 'layouts/footer' %>

app/views/pages/contact_us.html.erb
<%= render 'layouts/navbar', other_page: true %>
<!--page title start-->
<div class="rock_page_title_main">
  <%= render 'rock_page_title_bg' %>
  <div class="rock_page_title">
    <div class="container">
      <div class="rock_heading_div">
        <div class="rock_heading">
          <h1>Contáctanos</h1>
          <p>X</p>
        </div>
      </div>
      <div class="rock_pager">
        <ul>
          <li><a href="index.html">Home</a></li>
          <li><a href="">Contáctanos</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--page title end-->
<div class="clearfix"></div>
<div class="container">
  <div class="rock_contact">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-6 contact-form">
        <form role="form" id="contact-form" action="">
          <div class="form-group">
            <input type="text" name="name" class="form-control" id="uname" placeholder="Nombre">
          </div>
          <div class="form-group">
            <input type="email" name="_replyto" class="form-control" id="uemail" placeholder="Correo Electrónico">
          </div>
          <div class="form-group">
            <textarea rows="10" name="message" class="form-control" id="message" placeholder="Mensaje"></textarea>
          </div>
          <input type="submit" id="em_sub" class="btn btn-default btn-lg" value="Enviar Mensaje">
          <input type="hidden" name="_next" value="http://www.anacatalina.co" />
          <input type="hidden" name="_subject" value="Solicitud de contacto de AnaCatalina.co!" />
          <p id="err"></p>
        </form>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6">
        <div class="rock_contact_detail">
          <div>
            <p><i class="fa fa-envelope"></i> <a href="anacatalinacalderon@gmail.com?subject=Contacto Ana Catalina!&body">anacatalinacalderon@gmail.com</a></p>
            <p><i class="fa fa-mobile"></i> <a href="tel:+573007057090">+57 300 705 7090</a></p>
          </div>
          <div>
            <p><i class="fa fa-map-marker"></i> <a href="javascript:void(0);">Medellin, Colombia</a></p>
            <p><i class="fa fa-globe"></i> <a href="javascript:void(0);">www.anacatalina.co</a></p>
          </div>
        </div>
        <div class="rock_map">
          <iframe class="google-map" src="https://maps.google.sk/maps/ms?msa=0&amp;msid=210946297010027755543.0004c74af772bb9276d33&amp;ie=UTF8&amp;ll=6.252557,-75.568125&amp;spn=0,0&amp;t=m&amp;output=embed"></iframe>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="clearfix"></div>
<%= render 'layouts/footer' %>

<script>
  $( "#contact-form" ).on( "submit", function( event ) {
     event.preventDefault();
     var formData = $( this ).serialize();
     $.ajax({
       url: "//formspree.io/anacatalinacalderon@gmail.com",
       method: "POST",
       data: formData,
       dataType: "json"
     }).done(function(response) {
       $( '.contact-form' ).html("<h2 class='text-center'>¡Gracias por dejarme tu mensaje. Muy pronto nos pondremos en contacto!</h2>")
     });
   })
</script>

app/views/pages/events.html.erb
<%= render 'layouts/navbar', other_page: true %>
<!--page title start-->
<div class="rock_page_title_main">
  <%= render 'rock_page_title_bg' %>
  <div class="rock_page_title">
    <div class="container">
      <div class="rock_heading_div">
        <div class="rock_heading">
          <h1>Eventos</h1>
          <p>X</p>
        </div>
      </div>
      <div class="rock_pager">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Eventos", coming_events_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--page title end-->
<div class="clearfix"></div>
<div class="rock_margin_30"></div>
<div class="container">
  <div class="row">
    <% @events.each do |event| %>
      <div class="col-lg-6 col-md-6 col-sm-6">
        <div class="rock_main_event">
          <div class="rock_main_event_image"> <img src="<%= event.image.url(:medium) %>" alt="" />
          </div>
          <div class="rock_main_event_detail">
            <div class="rock_event_date">
              <div class="event_date">
                <h1><%= event.event_date.strftime("%d") %></h1>
                <p><%= event.event_date.strftime("%B") %></p>
              </div>
            </div>
            <h2><%= event.title %></h2>
            <div class="blog_entry_meta">
              <ul>
                <li><a href="javascript:void(0);" style="cursor: text;"><i class="fa fa-clock-o"></i> <%= event.start_hour.strftime("%l %p") %> - <%= event.end_hour.strftime("%l %p") %></a></li>
                <li><a href="javascript:void(0);" style="cursor: text;"><i class="fa fa-map-marker"></i><%= event.location.humanize %></a></li>
              </ul>
            </div>
            <p><%= event.description %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="clearfix"></div>
<%= render 'layouts/footer' %>

app/views/pages/gallery.html.erb
<%= render 'layouts/navbar', other_page: true %>
<!--page title start-->
<div class="rock_page_title_main">
  <%= render 'rock_page_title_bg' %>
  <div class="rock_page_title">
    <div class="container">
      <div class="rock_heading_div">
        <div class="rock_heading">
          <h1>Galería</h1>
          <p>X</p>
        </div>
      </div>
      <div class="rock_pager">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Galería", pictures_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--page title end-->
<div class="clearfix"></div>

<div class="container" style="margin-bottom: 50px;">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <% @galleries.each do |gallery| %>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
          <div class="rock_about_offer"> <img src="<%= gallery.avatar.url(:cover) %>" alt="offer" /> <%= link_to show_gallery_path(:gallery_id => gallery.id) do %> <h3><%= gallery.title %></h3> <% end %>
            <p><%= gallery.description %> </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="clearfix"></div>
<%= render 'layouts/footer' %>

app/views/pages/show_gallery.html.erb
<%= render 'layouts/navbar', other_page: true %>
<!--page title start-->
<div class="rock_page_title_main">
  <%= render 'rock_page_title_bg' %>
  <div class="rock_page_title">
    <div class="container">
      <div class="rock_heading_div">
        <div class="rock_heading">
          <h1><%= @gallery.title %></h1>
          <p>X</p>
        </div>
      </div>
      <div class="rock_pager">
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Galerías", pictures_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--page title end-->
<div class="clearfix"></div>
<div class="container">
  <div class="rock_main_gallery">
    <div class="main_gallery">
      <div class="main_gallery_tab">
        <ul>
          <li><a class="description-selector" href="javascript:void(0);"><%= @gallery.description %></a></li>
        </ul>
      </div>
      <div id="photo_tab" class="main_gallery_tab_content animated fadeInDown">
        <div class="row">

          <% @images.each do |image| %>
            <div class="col-lg-4 col-md-4 col-sm-4 main_gallery_item">
              <div class="rock_club_photo_slider_item">
                <div class="rock_club_photo_item"> <img src="<%= image.photo.url(:photo) %>" alt="" />
                  <div class="rock_club_photo_overlay">
                    <div class="photo_link animated fadeInDown"> <a class="fancybox" data-fancybox-group="group1" href="<%= image.photo.url %>"><i class="fa fa-search-plus"></i></a></div>
                    <a class="rock_club_photo_detail animated fadeInUp" href="">Ana Catalina</a> </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/footer' %>

<style>
  .description-selector {
    cursor: text;
  }
</style>