config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get 'coming_events' => 'pages#events'
  get 'blog' => 'pages#blog'
  get 'contact' => 'pages#contact_us'
  get 'pictures' => 'pages#gallery'
  get 'show_gallery' => 'pages#show_gallery'
  get 'about_me' => 'pages#about_me'
  resources :events
  resources :galleries
  resources :blog_entries
  resources :music_tracks
  resources :images
  resources :copies
  resources :slides
  devise_scope :user do
    get "/admin" => "devise/sessions#new"
  end
end

app/views/layouts/_footer.html.erb
<div class="rock_footer rock_padding_20">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="rock_footer_logo"> <img src="<%= asset_path('Logo1.png') %>" alt="footer logo" /> </div>
        <h3><%= @copies.footer_title_1 %></h3>
        <p><%= @copies.footer_text_1 %></p>
        <h3><%= @copies.footer_title_2 %></h3>
        <p><%= @copies.footer_text_2 %></p>
        <h3><%= @copies.footer_title_3 %></h3>
        <p><%= @copies.footer_text_3 %></p>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="rock_recent_post">
          <h3>Artículos Recientes</h3>
          <ul class="bxslider">
            <% @footer_blog_entries.each do |blog_entry| %>
              <li> <img src="<%= blog_entry.image.url(:thumb) %>" alt="post" />
                <div class="rock_post_detail"> <%= link_to blog_entry.title, blog_entry_path(blog_entry) %>
                  <p><span class="label label-default"><%= blog_entry.created_at.strftime("%B %d, %Y") %></span></p>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="rock_recent_post">
          <h3>Próximos Eventos</h3>
          <ul class="bxslider">
            <% @footer_events.each do |event| %>
              <li>
                <img src="<%= event.image.url(:thumb) %>" alt="post" />
                <div class="rock_post_detail"> <a href="javascript:void(0);" style="cursor: text;"><%= event.title %></a>
                  <p><span class="label label-default"><%= event.event_date.strftime("%B %d, %Y") %></span></p>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="rock_copyright">
  <div class="rock_copyright_bg">
    <section class="main">
      <div id="ri-grid2" class="ri-grid ri-grid-size-3">
        <ul>
          <!-- Background Images from AWS -->
          <% @footer_images.each do |background_image| %>
            <li><a href="#"><img src="<%= background_image.image.url(:medium) %>" alt="" /></a></li>
          <% end %>
        </ul>
      </div>
    </section>
  </div>
  <div class="rock_copyright_div">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-12">
          <p>Ana Catalina</p>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12">
          <div class="rock_social">
            <ul>
              <li><a href="https://www.facebook.com/AnaCatalina1" target="_blank"><i class="fa fa-facebook"></i></a></li>
              <li><a href="https://www.instagram.com/anacatalina_1/" target="_blank"><i class="fa fa-instagram"></i></a></li>
              <li><a href="https://twitter.com/AnaCatalina_1" target="_blank"><i class="fa fa-twitter"></i></a></li>
              <li><a href="https://www.youtube.com/channel/UCSiEHgtSPKJzhFnhRu3cXzQ" target="_blank"><i class="fa fa-youtube"></i></a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-5 col-md-8 col-sm-12 col-lg-offset-0 col-md-offset-2 col-sm-offset-0">
          <p>CopyRight @ 2016 Ana Catalina all right reserved </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<% if other_page == true %>
  <header id="rock_header_other_page">
<% else %>
  <header id="rock_header">
<% end %>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="col-lg-3 col-md-3 col-sm-12">
          <div class="rock_logo"><%= link_to "<img src='#{asset_path('Logo1.png')}' alt='logo' />".html_safe, root_path %></div>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-12">
          <div class="rock_menu_toggle navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">Menu <i class="fa fa-bars"></i></div>
          <div class="rock_menu">
            <ul class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <li><%= link_to "Quién soy?", about_me_path %></li>
              <li><%= link_to "Galería", pictures_path %></li>
              <li><%= link_to "Eventos", coming_events_path %></li>
              <li><%= link_to "Blog", blog_path %></li>
              <li><%= link_to "Contacto", contact_path %></li>
              <% if user_signed_in? %>
                <li class="active"><a>Admin</a>
                  <ul class="sub-menu">
                    <li><%= link_to "Slides", slides_path %></li>
                    <li><%= link_to "Textos", edit_copy_path(@copies) %></li>
                    <li><%= link_to "Galerías", galleries_path %></li>
                    <li><%= link_to "Música", music_tracks_path %></li>
                    <li><%= link_to "Eventos", events_path %></li>
                    <li><%= link_to "Blog", blog_entries_path %></li>
                    <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<!--header end-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ana Catalina</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  <meta name="description"  content="Ana Catalina WEB Oficial"/>
  <meta name="keywords" content="Ana Catalina Calderon, Ana Catalina Calderon Gomez, Ana Catalina, Minuto de Dios, Música, Música católica, Tu en mi, Evangelización">
  <meta name="author"  content="Ana Catalina"/>
  <meta name="MobileOptimized" content="320">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,400' rel='stylesheet' type='text/css'>

  <!-- Google Analytics Pixel -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-86746418-1', 'auto');
    ga('send', 'pageview');

  </script>
  <!-- End Google Analytics Pixel -->
</head>
<body data-no-turbolink="true">

<%= yield %>

</body>
</html>